linters:
  enable:
    - decorder

linters-settings:
  decorder:
    dec-order:
      - const
      - type
      - var
      - func
    disable-dec-order-check: false
    disable-dec-num-check: true
    ignore-underscore-vars: true
